### ISSUE TITLE
router.get('/', function(req, res) { ^  ReferenceError: router is not defined 

### ISSUE THREAD

**Issue by travexyz** [eashish93/youtube-downloader-app#5]
router.get('/', function(req, res) {
^

ReferenceError: router is not defined
    at Object.<anonymous> (...\youtube\routes\index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (*\youtube\app.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2020-10-07T17_52_56_078Z-debug.log

**Comment by travexyz** [comment]
closing for inactivity
